spring.application.name=SmartOps-Maintenance-System

spring.datasource.url=jdbc:mysql://localhost:3306/opmms
spring.datasource.username=user
spring.datasource.password=MysqlServer@3306

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081